// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockAnalyzer.Api.Data;

#nullable disable

namespace StockAnalyzer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockAnalyzer.Api.Data.CachedAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VolatilityScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "CreatedAt");

                    b.ToTable("CachedAnalyses");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdjustedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LearningWeightId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NewWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PreviousWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LearningWeightId");

                    b.ToTable("LearningAdjustments");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPositiveEvidence")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PredictionTargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightImpact")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FactorId");

                    b.HasIndex("PredictionTargetId");

                    b.ToTable("LearningEvidence");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("LearningFactors");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactorId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketRegime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FactorId");

                    b.ToTable("LearningWeights");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DataConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalAnalysisJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PredictionScore")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ticker");

                    b.HasIndex("Timestamp");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccuracyScore")
                        .HasColumnType("integer");

                    b.Property<decimal>("ActualPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvaluationResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PredictionTargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PredictionTargetId")
                        .IsUnique();

                    b.ToTable("PredictionEvaluations");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionPostMortem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailedAssumptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FutureImprovements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PredictionTargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("SucceededAssumptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatWasCorrect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatWasIncorrect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatWasMissed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PredictionTargetId")
                        .IsUnique();

                    b.ToTable("PredictionPostMortems");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LearningContextUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketRegime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId")
                        .IsUnique();

                    b.ToTable("PredictionSnapshots");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HigherEstimate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsEvaluated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LowerEstimate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ModerateEstimate")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("IsEvaluated");

                    b.HasIndex("PredictionId");

                    b.ToTable("PredictionTargets");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningAdjustment", b =>
                {
                    b.HasOne("StockAnalyzer.Api.Models.LearningWeight", "Weight")
                        .WithMany("Adjustments")
                        .HasForeignKey("LearningWeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningEvidence", b =>
                {
                    b.HasOne("StockAnalyzer.Api.Models.LearningFactor", "Factor")
                        .WithMany("Evidence")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockAnalyzer.Api.Models.PredictionTarget", "Target")
                        .WithMany("Evidence")
                        .HasForeignKey("PredictionTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factor");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningWeight", b =>
                {
                    b.HasOne("StockAnalyzer.Api.Models.LearningFactor", "Factor")
                        .WithMany("Weights")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factor");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionEvaluation", b =>
                {
                    b.HasOne("StockAnalyzer.Api.Models.PredictionTarget", "Target")
                        .WithOne("Evaluation")
                        .HasForeignKey("StockAnalyzer.Api.Models.PredictionEvaluation", "PredictionTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionPostMortem", b =>
                {
                    b.HasOne("StockAnalyzer.Api.Models.PredictionTarget", "Target")
                        .WithOne("PostMortem")
                        .HasForeignKey("StockAnalyzer.Api.Models.PredictionPostMortem", "PredictionTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionSnapshot", b =>
                {
                    b.HasOne("StockAnalyzer.Api.Models.Prediction", "Prediction")
                        .WithOne("Snapshot")
                        .HasForeignKey("StockAnalyzer.Api.Models.PredictionSnapshot", "PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionTarget", b =>
                {
                    b.HasOne("StockAnalyzer.Api.Models.Prediction", "Prediction")
                        .WithMany("Targets")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningFactor", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Weights");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.LearningWeight", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.Prediction", b =>
                {
                    b.Navigation("Snapshot");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("StockAnalyzer.Api.Models.PredictionTarget", b =>
                {
                    b.Navigation("Evaluation");

                    b.Navigation("Evidence");

                    b.Navigation("PostMortem");
                });
#pragma warning restore 612, 618
        }
    }
}
